name: phone_number_field
description: "A package that provides a Flutter widget for formatting and validating phone numbers in text fields."
version: 1.1.1
homepage: https://github.com/AbbosbekBotirjonovich/phone_number_field.git

environment:
  sdk: ^3.8.1
  flutter: ">=3.24.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  assets:
    - assets/countries.txt

topics:
  - intl-phone-number
  - country-picker
  - phone-number-formatter
